# Generated by Django 3.1.4 on 2020-12-15 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttribType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(default='', max_length=200)),
                ('mandatory', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='AttribValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DataObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(default='', max_length=200)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ied.attribute')),
            ],
        ),
        migrations.CreateModel(
            name='LogicalNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(default='', max_length=200)),
                ('data_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ied.dataobject')),
            ],
        ),
        migrations.CreateModel(
            name='LogicalDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(default='', max_length=200)),
                ('logical_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ied.logicalnode')),
            ],
        ),
        migrations.CreateModel(
            name='IED',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(default='', max_length=200)),
                ('logical_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ied.logicaldevice')),
            ],
        ),
        migrations.AddField(
            model_name='attribute',
            name='attrib_value',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ied.attribvalue'),
        ),
    ]
