# Generated by Django 3.1.4 on 2020-12-15 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ied', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribtype',
            name='desciption',
            field=models.CharField(default='', max_length=100),
        ),
    ]
