# Generated by Django 3.1.4 on 2020-12-15 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ied', '0002_attribtype_desciption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribtype',
            name='name',
            field=models.CharField(max_length=3, unique=True),
        ),
    ]
