# Generated by Django 3.1.4 on 2020-12-15 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ied', '0004_auto_20201215_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='attrib_value',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='ied.attribvalue'),
        ),
    ]
