# Generated by Django 3.1.4 on 2020-12-15 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ied', '0005_auto_20201215_2003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attribute',
            name='attrib_value',
        ),
        migrations.RemoveField(
            model_name='dataobject',
            name='attribute',
        ),
        migrations.RemoveField(
            model_name='ied',
            name='logical_device',
        ),
        migrations.RemoveField(
            model_name='logicaldevice',
            name='logical_node',
        ),
        migrations.RemoveField(
            model_name='logicalnode',
            name='data_object',
        ),
        migrations.AddField(
            model_name='attribute',
            name='data_object',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ied.dataobject'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attribvalue',
            name='attribute',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='ied.attribute'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dataobject',
            name='logical_node',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='ied.logicalnode'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='logicaldevice',
            name='logical_device',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ied.ied'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='logicalnode',
            name='logical_device',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='ied.logicaldevice'),
            preserve_default=False,
        ),
    ]
