# Generated by Django 3.1.4 on 2020-12-15 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ied', '0007_auto_20201215_2059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logicaldevice',
            old_name='logical_device',
            new_name='ied',
        ),
    ]
