# Generated by Django 3.1.4 on 2020-12-15 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ied', '0008_auto_20201215_2109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attribute',
            name='mandatory',
        ),
    ]
