# Generated by Django 3.1.4 on 2020-12-15 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ied', '0009_remove_attribute_mandatory'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='attrib_choice',
            field=models.CharField(choices=[('M', 'Mandatory'), ('O', 'Optional'), ('C', 'Conditional')], default='M', max_length=2),
        ),
    ]
