# Generated by Django 3.1.4 on 2020-12-26 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ied', '0013_auto_20201226_1841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logicaldevice',
            name='logical_node',
        ),
        migrations.AddField(
            model_name='logicaldevice',
            name='logical_node',
            field=models.ManyToManyField(to='ied.LogicalNode'),
        ),
    ]
