# Generated by Django 3.1.4 on 2020-12-26 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ied', '0015_auto_20201226_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logicaldevice',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
